account/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView
# namespace
app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html'), name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('register/', views.register, name='register'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image/', views.my_image, name='my_image'),
]

article/urls.py
from . import views, list_views
from django.urls import path

# namespace
app_name = 'article'

urlpatterns = [
    # 后台
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<id>/<slug>/', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('redit-article/<article_id>/', views.redit_article, name='redit_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag'),
    # 前台
    path('list-article-titles/', list_views.article_titles, name='article_titles'),
    path('list-article-titles/<username>/', list_views.article_titles, name='author_titles'),
    path('list-article-detail/<id>/<slug>/', list_views.article_detail, name='list_article_detail'),
    path('like-article/', list_views.like_article, name='like_article'),
    # 发表评论
    path('post-comment/<article_id>/', list_views.post_comment, name='post_comment'),
]

blog/urls.py
from . import views
from django.urls import path

# namespace
app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<article_id>', views.blog_acticle, name='blog_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
# 对于显示静态文件非常重要
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('blog/', include('blog.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
# Create your models here.


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column',
                             on_delete=models.CASCADE, verbose_name='作者')
    column = models.CharField('栏目', max_length=200)
    created = models.DateField('创建时间', auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name='tag', on_delete=models.CASCADE, verbose_name='作者')
    tag = models.CharField('标签', max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name='article',
                               on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField('标题', max_length=200)
    slug = models.SlugField('Slug', max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column',
                               on_delete=models.CASCADE, verbose_name='栏目')
    body = models.TextField()
    created = models.DateTimeField('创建时间', default=timezone.now)
    updated = models.DateTimeField('修改时间', auto_now=True)
    users_like = models.ManyToManyField(User, related_name='articles_like', blank=True, verbose_name='点赞')
    total_views = models.PositiveIntegerField('浏览量', default=0)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True, verbose_name='文章标签')

    class Meta:
        ordering = ['-updated']
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail', args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name='comments', on_delete=models.CASCADE, verbose_name='文章')
    commentator = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE, verbose_name='评论人')
    body = models.TextField()
    created = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag
from django.forms import TextInput


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ['column']


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ['title', 'body']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ['tag']

        widgets = {
            'tag': TextInput(attrs={'class': 'form-control form-control-sm'}),
        }

article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm
import json
# Create your views here.
"""这里编写的都是用户后台的视图：栏目管理/发布文章/文章管理"""


@login_required
@csrf_exempt
def article_column(request):
    """栏目列表 & 新增栏目"""
    if request.method == "GET":
        column_list = ArticleColumn.objects.filter(user=request.user)
        paginator = Paginator(column_list, 10)  # 实例化一个分页对象, 每页显示10个
        page = request.GET.get('page')  # 从URL通过get页码，如?page=3
        try:
            current_page = paginator.page(page)  # 获取指定页面内容，其参数必须>=1的整数
            columns = current_page.object_list  # 获取当前页对应的所有记录
        except PageNotAnInteger:  # 页码不是整数，捕获异常
            current_page = paginator.page(1)
            columns = current_page.object_list
        except EmptyPage:  # 页码为空，捕获异常
            current_page = paginator.page(paginator.num_pages)  # 返回页数
            columns = current_page.object_list
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {"columns": columns, "column_form": column_form,
                                                                      "page": current_page})
    if request.method == "POST":
        column_name = request.POST['column']
        if column_name:
            columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
            if columns:
                return HttpResponse('2')
            else:
                ArticleColumn.objects.create(user=request.user, column=column_name)
                return HttpResponse('1')
        else:
            return HttpResponse('3')


@login_required
@require_POST
@csrf_exempt
def rename_article_column(request):
    """修改栏目"""
    column_name = request.POST["column_name"]
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required
@require_POST
@csrf_exempt
def del_article_column(request):
    """删除栏目"""
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required
@csrf_exempt
def article_post(request):
    """新增文章"""
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, 'article/column/article_post.html',
                      {'article_post_form': article_post_form, 'article_columns': article_columns,
                       'article_tags': article_tags})


@login_required
def article_list(request):
    """文章列表"""
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)  # 实例化一个分页对象, 每页显示10个
    page = request.GET.get('page')  # 从URL通过get页码，如?page=3
    try:
        current_page = paginator.page(page)     # 获取指定页面内容，其参数必须>=1的整数
        articles = current_page.object_list  # 获取当前页对应的所有记录
    except PageNotAnInteger:        # 页码不是整数，捕获异常
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:       # 页码为空，捕获异常
        current_page = paginator.page(paginator.num_pages)      # 返回页数
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {'articles': articles, 'page': current_page})


@login_required
def article_detail(request, id, slug):
    """文章详情"""
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, 'article/column/article_detail.html', {'article': article})


@login_required
@require_POST
@csrf_exempt
def del_article(request):
    """删除文章"""
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required
@csrf_exempt
def redit_article(request, article_id):
    """修改文章"""
    if request.method == "GET":
        article_columns = request.user.article_column.all()     # 该用户的所有栏目
        article = ArticlePost.objects.get(id=article_id)        # 当前ID的这篇文章的实例
        this_article_form = ArticlePostForm(initial={"title": article.title})  # 当前ID的这篇文章实例的表单，初始标题
        this_article_column = article.column        # 当前ID的这篇文章实例的默认栏目
        user_tags = request.user.tag.all()       # 该用户的所有标签，注意：不是这篇文章的所有标签
        return render(request, 'article/column/redit_article.html', {"article": article,
                                                                     "article_columns": article_columns,
                                                                     "this_article_column": this_article_column,
                                                                     "this_article_form": this_article_form,
                                                                     'user_tags': user_tags})
    else:
        edited_article = ArticlePost.objects.get(id=article_id)
        edited_article.article_tag.clear()      # 先清空此文章的所有标签，如果不清空，就永远是累加
        try:
            edited_article.column = request.user.article_column.get(id=request.POST['column_id'])
            edited_article.title = request.POST['title']
            edited_article.body = request.POST['body']
            edited_article.save()
            tags = request.POST['tags']
            if tags:
                for atag in json.loads(tags):
                    tag = request.user.tag.get(tag=atag)
                    edited_article.article_tag.add(tag)
            return HttpResponse("1")
        except:
            return HttpResponse("2")


@login_required
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html', {'article_tags': article_tags,
                                                             'article_tag_form': article_tag_form})
    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("数据没有被保存")
        else:
            return HttpResponse("对不起，表单不合法")


@login_required
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

templates/article/list/article_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load article_tags %}
{% block title %}文章详情{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% with total_likes=article.users_like.count users_like=article.users_like.all %}
                {#     内置标签（赋值语句）：总的点赞数total_likes/该文章的所有点赞用户users_like#}
                <header>
                    <h3 class="text-center mt-2 mb-3">{{ article.title }}</h3>
                    <p class="text-center">小编：
                        <span class="badge badge-light">
                <a href="{% url 'article:author_titles' article.author.username %}">{{ article.author.username }}</a>
                </span> |
                        发布时间：<span class="badge badge-light">{{ article.created | date:"Y-m-d h:i" }}</span> |
                        栏目：<span class="badge badge-info">{{ article.column }}</span> |
                        <span><i class="fa fa-fw fa-thumbs-o-up"></i>{{ total_likes }}个点赞</span> |
                        <i class="fa fa-fw fa-eye"></i>浏览：<span>{{ article.total_views }}</span>
                    </p>
                </header>

                <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />

                <div id="editormd-view">
        <textarea id="append-test" style="display: none;">
{{ article.body }}
        </textarea>
                </div>

                <div>
                    <p class="text-center">
                        <a onclick="like_article({{ article.id }}, 'like')" href="#" class="btn btn-success">
                            <i class="fa fa-fw fa-thumbs-o-up"></i>点赞
                        </a>
                        <a onclick="like_article({{ article.id }}, 'unlike')" href="#" class="btn btn-danger ml-4 ">
                            <i class="fa fa-fw fa-thumbs-o-down"></i>鸡蛋
                        </a>
                    </p>
                </div>
                <div>
                    <p class="text-center">
                        <strong>点赞本文的读者：</strong>
                        {% for user in users_like %}
                            <span class="badge badge-light">{{ user.username }}</span>
                        {% empty %}
                            <p class="text-center">还没有人对此文章表态</p>
                        {% endfor %}
                    </p>
                </div>

                <!-- 发表评论 -->
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form action="{% url 'article:post_comment' article.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body"><strong>我也要发言：</strong></label>
                                <textarea type="text" class="form-control" id="body" name="body" rows="2"></textarea>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary ">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'account:user_login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}

                <!-- 显示评论 -->
                <h4>共有{{ comments.count }}条评论</h4>
                <div>
                    {% for comment in comments %}
                        <hr>
                        <p>
                            <strong style="color: pink">
                                {{ comment.commentator }}
                            </strong> 于
                            <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
                        </p>
                        <pre style="font-family: inherit; font-size: 1em;">
{{ comment.body }}</pre>
                    {% endfor %}
                </div>
            {% endwith %}
        </div>

        <div class="col-md-4">

            <div class="card mb-3">
                <h5 class="card-header"><i class="fa fa-fw fa-thumbs-up text-danger"></i> 最受欢迎的文章（浏览量）</h5>
                <div class="card-body small">
                    {% show_total_views 5 as total_views %}
                    <ol>
                        {% for hot_article in total_views %}
                            <li class="mb-2">
                                <a href="{{hot_article.get_url_path}}">{{ hot_article.title | truncatechars:30 }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>

            {% show_latest_articles 5 %}

            <div class="card mb-3">
                <h5 class="card-header"><i class="fa fa-fw fa-bullhorn text-danger"></i> 最多评论的文章</h5>
                <div class="card-body small">
                    {% most_commented_articles 5 as most_comments %}
                    <ol>
                        {% for comment_article in most_comments %}
                            <li class="mb-2">
                                <a href="{{comment_article.get_url_path}}">{{ comment_article.title | truncatechars:30 }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>

            <div class="card mb-3">
                <h5 class="card-header"><i class="fa fa-fw fa-file-text-o text-danger"></i> 推荐相似文章</h5>
                <div class="card-body small">
                    <ol>
                        {% for similar in similar_articles %}
                            <li class="mb-2">
                                <a href="{{similar.get_url_path}}">{{ similar.title | truncatechars:30 }}</a>
                            </li>
                        {% empty %}
                            对不起，没有相似文章
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script>
        $(function () {
           editormd.markdownToHTML("editormd-view", {
               htmlDecode: "style,script,iframe",
               emoji: true,
               taskList: true,
               tex: true,   //默认不解析
               flowChart: true,     //默认不解析
               sequenceDiagram: true,   //默认不解析
           });
        });
        function like_article(id, action) {
            $.ajax({
                url: "{% url 'article:like_article' %}",
                type: "POST",
                data: {"id": id, "action": action},
                success: function (e) {
                  if(e==="1"){
                      layer.msg("感谢点赞");
                      window.location.reload();
                  }else if (e==="0"){
                      layer.alert("对不起，您已经点过赞了！",{icon: 0,});
                  } else {
                      layer.msg("我会继续努力");
                      window.location.reload();
                  }
                },
            });
        }
    </script>
{% endblock %}

templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %}文章列表{% endblock %}
{% block content %}
    <div class="row justify-content-center mb-3">
        <h2>阅读，丰富头脑，善化行为</h2>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="alert alert-primary" role="alert">
                这里有 <span class="font-weight-bold text-success">{% total_articles %}</span> 篇文章供你阅读
            </div>
            {% for article in articles %}
                <div class="card border-light mb-4 small">
                    <h5 class="card-header border-0">
                        <span class="text-secondary">({{ forloop.counter }})</span>
                        <a href="{{ article.get_url_path }}" class="text-dark">{{ article.title | truncatechars:28 }}</a>
                    </h5>
                    <div class="card-body">
                        <h5 class="card-title"><span class="badge badge-warning">{{ article.column }}</span></h5>
                        <div class="card-text text-secondary">
                            {{ article.body | striptags | truncatechars:80 | linebreaks }}
                        </div>
                        <a href="{{ article.get_url_path }}" class="btn btn-outline-info btn-sm">阅读本文</a>
                    </div>
                    <div class="card-footer border-0">
                        <small class="text-muted pull-left">作者：
                            <a href="{% url 'article:author_titles' article.author.username %}" class="badge badge-primary">
                                {{ article.author.username }}
                            </a>
                        </small>
                        <!-- 显示浏览量 -->
                        <small class="text-muted pull-left ml-3">
                            浏览：<span class="badge badge-success badge-pill">{{ article.total_views }}</span>
                        </small>
                        <small class="pull-right">
                            <span class="text-primary">{{ article.created | date:"Y-m-d h:i:s" }} 发布</span> |
                            <span class="text-danger">{{ article.updated | date:"Y-m-d h:i:s" }} 更新</span>
                        </small>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-md-4">
            <div class="card mb-3">
                <h5 class="card-header"><i class="fa fa-fw fa-thumbs-up text-danger"></i> 最受欢迎的文章（浏览量）</h5>
                <div class="card-body small">
                    {% show_total_views 5 as total_views %}
                    <ol>
                        {% for hot_article in total_views %}
                            <li class="mb-2">
                                <a href="{{hot_article.get_url_path}}">{{ hot_article.title | truncatechars:30 }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>

            {% show_latest_articles 5 %}

            <div class="card mb-3">
                <h5 class="card-header"><i class="fa fa-fw fa-bullhorn text-danger"></i> 最多评论的文章</h5>
                <div class="card-body small">
                    {% most_commented_articles 5 as most_comments %}
                    <ol>
                        {% for comment_article in most_comments %}
                            <li class="mb-2">
                                <a href="{{comment_article.get_url_path}}">{{ comment_article.title | truncatechars:30 }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>

    {% include "paginator.html" %}



{% endblock %}

templates/article/list/author_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %}文章列表{% endblock %}
{% block content %}
    <div class="row text-center justify-content-center mb-3">
        <h2>{{ user.username }}的所有文章</h2>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% for article in articles %}
                    <div class="card border-light mb-4 small">
                        <h5 class="card-header border-0">
                            <span class="text-secondary">({{ forloop.counter }})</span>
                            <a href="{{ article.get_url_path }}" class="text-dark">{{ article.title | truncatechars:28 }}</a>
                        </h5>
                        <div class="card-body">
                            <h5 class="card-title"><span class="badge badge-warning">{{ article.column }}</span></h5>
                            <div class="card-text text-secondary">
                                {{ article.body | truncatechars:80 | linebreaks }}
                            </div>
                            <a href="{{ article.get_url_path }}" class="btn btn-outline-info btn-sm">阅读本文</a>
                        </div>
                        <div class="card-footer border-0">
                            <small class="text-muted pull-left">作者：
                                <a href="{% url 'article:author_titles' article.author.username %}" class="badge badge-primary">
                                    {{ article.author.username }}
                                </a>
                            </small>
                            <!-- 显示浏览量 -->
                            <small class="text-muted pull-left ml-3">
                                浏览：<span class="badge badge-success badge-pill">{{ article.total_views }}</span>
                            </small>
                            <small class="pull-right">
                                <span class="text-primary">{{ article.created | date:"Y-m-d h:i:s" }} 发布</span> |
                                <span class="text-danger">{{ article.updated | date:"Y-m-d h:i:s" }} 更新</span>
                            </small>
                        </div>
                    </div>
                {% endfor %}
                {% include "paginator.html" %}
            </div>
            <div class="col-md-4">
                <div class="card text-center small">
                    <h5 class="card-header">{{ user.username }}</h5>
                    <div class="card-body">
                        {% if userinfo.photo %}
                            <img src="{{ userinfo.photo | striptags }}" class="img-thumbnail rounded-circle" id="my_photo" name="user_face">
                        {% else %}
                            <img src="{% static 'images/touxiang.jpg' %}" class="img-thumbnail rounded-circle" id="my_photo" name="user_face">
                        {% endif %}
                        <h6 class="card-title mt-2">共发表文章 {% author_total_articles user %} 篇</h6>
                        {% if userinfo %}
                            <p class="card-text">{{ userinfo.company }}</p>
                        {% else %}
                            <p class="card-text">这个作者太懒了，什么也没有留下。</p>
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        {{ userinfo.profession }}
                    </div>
                </div>

                <div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/list/latest_articles.html
<div class="card mb-3">
    <h5 class="card-header"><i class="fa fa-fw fa-fire text-danger"></i> 最新发布的文章</h5>
    <div class="card-body small">
        <ol>
            {% for article in latest_articles %}
                <li class="mb-2">
                    <a href="{{article.get_url_path}}">{{ article.title | truncatechars:30 }}</a>
                </li>
            {% endfor %}
        </ol>
    </div>
</div>