article/urls.py
from . import views, list_views
from django.urls import path

# namespace
app_name = 'article'

urlpatterns = [
    # 后台
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<id>/<slug>/', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('redit-article/<article_id>/', views.redit_article, name='redit_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag'),
    # 前台
    path('list-article-titles/', list_views.article_titles, name='article_titles'),
    path('list-article-titles/<username>/', list_views.article_titles, name='author_titles'),
    path('list-article-detail/<id>/<slug>/', list_views.article_detail, name='list_article_detail'),
    path('like-article/', list_views.like_article, name='like_article'),
    # 发表评论
    path('post-comment/<article_id>/', list_views.post_comment, name='post_comment'),
]

blog/urls.py
from . import views
from django.urls import path

# namespace
app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<article_id>', views.blog_acticle, name='blog_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
# 对于显示静态文件非常重要
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('blog/', include('blog.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
# Create your models here.


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column',
                             on_delete=models.CASCADE, verbose_name='作者')
    column = models.CharField('栏目', max_length=200)
    created = models.DateField('创建时间', auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name='tag', on_delete=models.CASCADE, verbose_name='作者')
    tag = models.CharField('标签', max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name='article',
                               on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField('标题', max_length=200)
    slug = models.SlugField('Slug', max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column',
                               on_delete=models.CASCADE, verbose_name='栏目')
    body = models.TextField()
    created = models.DateTimeField('创建时间', default=timezone.now)
    updated = models.DateTimeField('修改时间', auto_now=True)
    users_like = models.ManyToManyField(User, related_name='articles_like', blank=True, verbose_name='点赞')
    total_views = models.PositiveIntegerField('浏览量', default=0)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True, verbose_name='文章标签')

    class Meta:
        ordering = ['-updated']
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail', args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name='comments', on_delete=models.CASCADE, verbose_name='文章')
    commentator = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE, verbose_name='评论人')
    body = models.TextField()
    created = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag
from django.forms import TextInput


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ['column']


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ['title', 'body']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ['tag']

        widgets = {
            'tag': TextInput(attrs={'class': 'form-control form-control-sm'}),
        }

article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm
import json
# Create your views here.
"""这里编写的都是用户后台的视图：栏目管理/发布文章/文章管理"""


@login_required
@csrf_exempt
def article_column(request):
    """栏目列表 & 新增栏目"""
    if request.method == "GET":
        column_list = ArticleColumn.objects.filter(user=request.user)
        paginator = Paginator(column_list, 10)  # 实例化一个分页对象, 每页显示10个
        page = request.GET.get('page')  # 从URL通过get页码，如?page=3
        try:
            current_page = paginator.page(page)  # 获取指定页面内容，其参数必须>=1的整数
            columns = current_page.object_list  # 获取当前页对应的所有记录
        except PageNotAnInteger:  # 页码不是整数，捕获异常
            current_page = paginator.page(1)
            columns = current_page.object_list
        except EmptyPage:  # 页码为空，捕获异常
            current_page = paginator.page(paginator.num_pages)  # 返回页数
            columns = current_page.object_list
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {"columns": columns, "column_form": column_form,
                                                                      "page": current_page})
    if request.method == "POST":
        column_name = request.POST['column']
        if column_name:
            columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
            if columns:
                return HttpResponse('2')
            else:
                ArticleColumn.objects.create(user=request.user, column=column_name)
                return HttpResponse('1')
        else:
            return HttpResponse('3')


@login_required
@require_POST
@csrf_exempt
def rename_article_column(request):
    """修改栏目"""
    column_name = request.POST["column_name"]
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required
@require_POST
@csrf_exempt
def del_article_column(request):
    """删除栏目"""
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required
@csrf_exempt
def article_post(request):
    """新增文章"""
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, 'article/column/article_post.html',
                      {'article_post_form': article_post_form, 'article_columns': article_columns,
                       'article_tags': article_tags})


@login_required
def article_list(request):
    """文章列表"""
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)  # 实例化一个分页对象, 每页显示10个
    page = request.GET.get('page')  # 从URL通过get页码，如?page=3
    try:
        current_page = paginator.page(page)     # 获取指定页面内容，其参数必须>=1的整数
        articles = current_page.object_list  # 获取当前页对应的所有记录
    except PageNotAnInteger:        # 页码不是整数，捕获异常
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:       # 页码为空，捕获异常
        current_page = paginator.page(paginator.num_pages)      # 返回页数
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {'articles': articles, 'page': current_page})


@login_required
def article_detail(request, id, slug):
    """文章详情"""
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, 'article/column/article_detail.html', {'article': article})


@login_required
@require_POST
@csrf_exempt
def del_article(request):
    """删除文章"""
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required
@csrf_exempt
def redit_article(request, article_id):
    """修改文章"""
    if request.method == "GET":
        article_columns = request.user.article_column.all()     # 该用户的所有栏目
        article = ArticlePost.objects.get(id=article_id)        # 当前ID的这篇文章的实例
        this_article_form = ArticlePostForm(initial={"title": article.title})  # 当前ID的这篇文章实例的表单，初始标题
        this_article_column = article.column        # 当前ID的这篇文章实例的默认栏目
        user_tags = request.user.tag.all()       # 该用户的所有标签，注意：不是这篇文章的所有标签
        return render(request, 'article/column/redit_article.html', {"article": article,
                                                                     "article_columns": article_columns,
                                                                     "this_article_column": this_article_column,
                                                                     "this_article_form": this_article_form,
                                                                     'user_tags': user_tags})
    else:
        edited_article = ArticlePost.objects.get(id=article_id)
        edited_article.article_tag.clear()      # 先清空此文章的所有标签，如果不清空，就永远是累加
        try:
            edited_article.column = request.user.article_column.get(id=request.POST['column_id'])
            edited_article.title = request.POST['title']
            edited_article.body = request.POST['body']
            edited_article.save()
            tags = request.POST['tags']
            if tags:
                for atag in json.loads(tags):
                    tag = request.user.tag.get(tag=atag)
                    edited_article.article_tag.add(tag)
            return HttpResponse("1")
        except:
            return HttpResponse("2")


@login_required
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html', {'article_tags': article_tags,
                                                             'article_tag_form': article_tag_form})
    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("数据没有被保存")
        else:
            return HttpResponse("对不起，表单不合法")


@login_required
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}栏目管理 | 管理后台{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mt-2 mb-2">
        <div class="input-group input-group-sm col-6">
            <input type="text" class="form-control" placeholder="请输入栏目名称" aria-label="Recipient's username" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button"><i class="fa fa-fw fa-search"></i>搜索</button>
            </div>
        </div>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <button class="btn btn-sm btn-success" id="add_column" onclick="add_column()">
                    <i class="fa fa-fw fa-plus"></i> 新增栏目
                </button>
            </div>
        </div>
    </div>
    <table class="table table-sm small table-hover">
        <tr class="bg-light font-weight-bold">
            <td>序号</td>
            <td>栏目名称</td>
            <td>文章数量</td>
            <td>创建时间</td>
            <td width="7%">操作</td>
        </tr>
        {% for column in columns %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ column.column }}</td>
                <td>{{ column.article_column.count }} 篇</td>
                <td>{{ column.created | date:"Y-m-d" }}</td>
                <td class="text-nowrap">
                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                        <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})">
                            <i class="fa fa-fw fa-pencil"></i>
                        </a>
                        <a name="delete" href="javascript:" onclick="delete_column(this, {{ column.id }})">
                            <i class="fa fa-fw fa-trash-o text-danger ml-2"></i>
                        </a>
                    </div>
                </td>
            </tr>
        {% empty %}
            <p class="alert alert-danger">还没有设置栏目，太懒了。</p>
        {% endfor %}
    </table>

    {% include "paginator.html" %}

{% endblock %}

{% block js %}
    <script type="text/javascript">
        function add_column() {
            var index = layer.open({
                type: 1,
                skin: 'layui-layer-rim', //样式类名
                shadeClose: true,
                area: ['360px', '210px'],
                title: "新增栏目",
                content: '<div class="text-center" style="margin-top:20px"><p>请输入新的' +
                    '栏目名称</p><p>{{ column_form.column }}</p></div>',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    var column_name = $('#id_column').val();
                    $.ajax({
                        url: '{% url "article:article_column" %}',
                        type: 'POST',
                        data: {"column": column_name},
                        success: function (e) {
                            if(e==="1"){
                                parent.location.reload();
                            }if(e==="3"){
                                layer.msg("不能为空")
                            }else{
                                layer.msg("此项目已有，请更换名称")
                            }
                        },
                    });
                },
                btn2: function (index, layero) {
                    layer.close(index)
                }
            });
        }
        function edit_column(the, column_id) {
            var tr = the.parentNode.parentNode.parentNode;
            var name = $(tr).find('td:eq(1)').text().replace(/(^\s*)|(\s*$)/g, "");
            var index = layer.open({
                type: 1,
                skin: 'layui-layer-rim', //样式类名
                shadeClose: true,
                area: ['360px', '210px'],
                title: "编辑栏目",
                content: '<div class="text-center" style="margin-top:20px"><p>请编辑' +
                    '栏目名称</p><p><input type="text" id="new_name" value="'+name+'"></p></div>',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                     var new_name = $("#new_name").val();
                    $.ajax({
                        url: "{% url 'article:rename_article_column' %}",
                        type: "POST",
                        data: {"column_id": column_id, "column_name": new_name},
                        success: function (e) {
                            if (e==="1"){
                                parent.location.reload();
                                layer.msg("修改成功");
                            }else {
                                layer.msg("新的名字没有保存，修改失败");
                            }
                        },
                    });
                },
            });
        }
        function delete_column(the, column_id) {
            var tr = the.parentNode.parentNode.parentNode;
            var name = $(tr).find('td:eq(1)').text().replace(/(^\s*)|(\s*$)/g, "");
            layer.open({
                type: 1,
                skin: 'layui-layer-rim', //样式类名
                shadeClose: true,
                area: ['360px', '170px'],
                title: "删除栏目",
                content: '<div class="text-center" style="margin-top:24px"><p>是否' +
                    '确定删除{'+name+'}</p></div>',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    $.ajax({
                        url: "{% url 'article:del_article_column' %}",
                        type: "POST",
                        data: {"column_id": column_id},
                        success: function (e) {
                            if (e==="1"){
                                parent.location.reload();
                                layer.msg("删除成功");
                            }else {
                                layer.msg("删除失败");
                            }
                        },
                    });
                },
            });
        }
    </script>
{% endblock %}

templates/article/column/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}文章详情 | 管理后台{% endblock %}

{% block content %}
    <header>
        <h3 class="text-center mt-2 mb-3">{{ article.title }}</h3>
        <p class="text-center">小编：<span class="badge badge-light">{{ user.username }}</span> |
            发布时间：<span class="badge badge-light">{{ article.created | date:"Y-m-d h:i" }}</span> |
            栏目：<span class="badge badge-info">{{ article.column }}</span>
        </p>
        <p class="text-center">
            {% if article.article_tag.all %}
                <strong>标签：</strong>
                {% for tag in article.article_tag.all %}
                    <span class="badge badge-primary">{{ tag }}</span>
                {% endfor %}
            {% endif %}
        </p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />

    <div id="editormd-view">
        <textarea id="append-test" style="display: none;">
{{ article.body }}
        </textarea>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script>
        $(function () {
           editormd.markdownToHTML("editormd-view", {
               htmlDecode: "style,script,iframe",
               emoji: true,
               taskList: true,
               tex: true,   //默认不解析
               flowChart: true,     //默认不解析
               sequenceDiagram: true,   //默认不解析
           });
        });
    </script>
{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}发布文章 | 管理后台{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}
{% block content %}
    <div class="ml-1">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row mt-1">
                <div class="col-md-2 text-right"><span>标题：</span></div>
                <div class="col-md-6 text-left" id="form_g1"><span>{{ article_post_form.title }}</span></div>
            </div>
            <div class="row mt-1">
                <div class="col-md-2 text-right"><span>栏目：</span></div>
                <div class="col-md-4 text-left" id="form_g2">
                    <select id="which_column" class="form-control form-control-sm">
                        {% for column in article_columns %}
                            <option value="{{ column.id }}">{{ column.column }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col-md-2 text-right"><span>标签：</span></div>
                <div class="col-md-10 text-left" id="form_g2">
                    {% for tag in article_tags %}
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input"
                                       id="{{ tag.id }}" value="{{ tag.tag }}" name="article_tag">{{ tag.tag }}
                            </label>
                        </div>
                    {% empty %}
                        您还没有文章标签，请先<a href="{% url 'article:article_tag' %}">添加标签</a>
                    {% endfor %}
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-md-2 text-right"><span>内容：</span></div>
                <div class="col-md-2 text-left"><input type="button" class="btn btn-primary btn-block btn-sm" value="发 布 文 章" onclick="publish_article()"></div>
            </div>
            <div class="row mt-4 mb-2">
                <div class="col-md-10" id="editormd">
                    <textarea style="display: none;" id="id_body"></textarea>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
    <script type="text/javascript">
        $("#form_g1").addClass("form-group");
        $("#form_g2").addClass("form-group");
        $("#id_title").addClass("form-control form-control-sm");
        $("#id_body").addClass("form-control form-control-sm");
        
        function publish_article() {
            var title = $("#id_title").val();
            var column_id = $("#which_column").val();
            var body = $("#id_body").val();
            var article_tags = [];
            $.each($("input[name='article_tag']:checked"),function () {
                article_tags.push($(this).val());
            });
            $.ajax({
                url: "{% url 'article:article_post' %}",
                type: "POST",
                data: {"title": title, "body": body, "column_id":column_id, "tags": JSON.stringify(article_tags)},
                success:function (e) {
                    if (e==="1"){
                        layer.msg("发布成功");
                        location.href = "{% url 'article:article_list' %}";
                    }else if(e==="2"){
                        layer.msg("对不起，发布失败")
                    }else {
                        layer.msg("有必填字段为空，无法提交")
                    }
                },
            });
        }
        $(function () {
            var editor = editormd("editormd", {
                width: "100%",
                height: 300,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}",
            });
        });
    </script>
{% endblock %}

templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}修改文章{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}
{% block content %}
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="row mt-1">
                <div class="col-md-2 text-right"><span>标题：</span></div>
                <div class="col-md-6 text-left" id="form_g1"><span>{{ this_article_form.title }}</span></div>
            </div>
            <div class="row mt-1">
                <div class="col-md-2 text-right"><span>栏目：</span></div>
                <div class="col-md-4 text-left" id="form_g2">
                    <select id="which_column" class="form-control form-control-sm">
                        {% for column in article_columns %}
                            {% if this_article_column == column %}
                                <option value="{{ column.id }}" selected="selected">{{ column.column }}</option>
                            {% else %}
                                <option value="{{ column.id }}">{{ column.column }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col-md-2 text-right"><span>标签：</span></div>
                <div class="col-md-10 text-left" id="form_g2">
                    {% for tag in user_tags %}
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                {% if tag in article.article_tag.all %}
                                    <input type="checkbox" class="form-check-input" checked
                                           id="{{ tag.id }}" value="{{ tag.tag }}" name="article_tag">{{ tag.tag }}
                                {% else %}
                                    <input type="checkbox" class="form-check-input"
                                           id="{{ tag.id }}" value="{{ tag.tag }}" name="article_tag">{{ tag.tag }}
                                {% endif %}
                            </label>
                        </div>
                    {% empty %}
                        您还没有文章标签，请先<a href="{% url 'article:article_tag' %}">添加标签</a>
                    {% endfor %}
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-md-2 text-right"><span>内容：</span></div>
                <div class="col-md-2 text-left"><input type="button" class="btn btn-primary btn-block btn-sm"
                                                       value="重 新 发 布" onclick="redit_article()"></div>
            </div>
            <div class="row mt-4 mb-2">
                <div class="col-md-10" id="editormd">
                    <textarea style="display: none;" id="id_body">
{{ article.body }}
                    </textarea>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript">
        $("#form_g1").addClass("form-group");
        $("#form_g2").addClass("form-group");
        $("#id_title").addClass("form-control form-control-sm");
        $("#id_body").addClass("form-control form-control-sm");

        $(function () {
           var editor = editormd("editormd", {
              width: "100%",
              height: 300,
              path: "{% static 'editor/lib/' %}",
           });
        });
        function redit_article() {
            var title = $("#id_title").val();
            var column_id = $("#which_column").val();
            var body = $("#id_body").val();
            var article_tags = [];
            $.each($("input[name='article_tag']:checked"),function () {
                article_tags.push($(this).val());
            });
            $.ajax({
               url: "{% url 'article:redit_article' article.id %}",
               type: "POST",
               data: {"title": title, "column_id": column_id, "body": body, "tags": JSON.stringify(article_tags)},
               success: function (e) {
                  if (e==="1"){
                      layer.msg("修改成功");
                      location.href = "{% url 'article:article_list' %}";
                  }else {
                      layer.msg("修改失败");
                  }
               } ,
            });
        }
    </script>
{% endblock %}