account/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView
# namespace
app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html'), name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('register/', views.register, name='register'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image/', views.my_image, name='my_image'),
]

article/urls.py
from . import views, list_views
from django.urls import path

# namespace
app_name = 'article'

urlpatterns = [
    # 后台
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<id>/<slug>/', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('redit-article/<article_id>/', views.redit_article, name='redit_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag'),
    # 前台
    path('list-article-titles/', list_views.article_titles, name='article_titles'),
    path('list-article-titles/<username>/', list_views.article_titles, name='author_titles'),
    path('list-article-detail/<id>/<slug>/', list_views.article_detail, name='list_article_detail'),
    path('like-article/', list_views.like_article, name='like_article'),
    # 发表评论
    path('post-comment/<article_id>/', list_views.post_comment, name='post_comment'),
]

blog/urls.py
from . import views
from django.urls import path

# namespace
app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<article_id>', views.blog_acticle, name='blog_detail'),
]

course/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
# namespace
app_name = 'course'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='course/about.html'), name='about'),
    path('course-list/', views.CourseListView.as_view(), name='course_list'),
    path('manage-course/', views.ManageCourseListView.as_view(), name='manage_course'),
    path('create-course/', views.CreateCourseView.as_view(), name='create_course'),
    path('delete-course/<pk>', views.DeleteCourseView.as_view(), name='delete_course'),
    path('create-lesson/', views.CreateLessonView.as_view(), name='create_lesson'),
]

image/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'image'

urlpatterns = [
    path('list-images/', views.list_images, name='list_images'),
    path('upload-image/', views.upload_image, name='upload_image'),
    path('del-image/', views.del_image, name='del_image'),
    path('images/', views.falls_images, name='falls_images'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
# 对于显示静态文件非常重要
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('blog/', include('blog.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'layer/theme/default/layer.css' %}">
    {% block css %}{% endblock %}
    <style>
        .layui-layer { font-size:0.875rem;}
        .layui-layer a:not([href]):not([tabindex]) { color:#FFF;}
        .layui-layer a:not([href]):not([tabindex]):last-child { color:#333;}
        .layui-layer a.layui-layer-btn0:not([href]):not([tabindex]):last-child { color:#FFF;}
    </style>
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'dist/js/popper.min.js' %}"></script>
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/theme/layer.js' %}"></script>
{% block js %}{% endblock %}
</html>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4" role="navigation">
        <a class="navbar-brand" href="{% url 'home' %}">Bo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:blog_title' %}">博客</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_titles' %}">文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'image:falls_images' %}">美图</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'course:course_list' %}">课程</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'course:about' %}">关于</a>
                </li>
            </ul>
            <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-fw fa-user-circle-o"></i>
                            {% if user.last_name %}
                                <span class="small">{{ user.last_name }}{{ user.first_name }}</span>
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'account:my_information' %}">
                                <i class="fa fa-fw fa-user"></i> 个人中心
                            </a>
                            <a class="dropdown-item" href="{% url 'account:edit_my_information' %}">
                                <i class="fa fa-fw fa-pencil"></i> 修改信息
                            </a>
                            <div class="dropdown-divider"></div>
                             <a class="dropdown-item" href="{% url 'article:article_column' %}">
                                <i class="fa fa-fw fa-dashboard"></i> 后台管理
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account:user_logout' %}">
                                <i class="fa fa-fw fa-sign-out"></i> 账号退出
                            </a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_login' %}">
                            <i class="fa fa-fw fa-sign-in"></i>请登录
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:register' %}">
                            <i class="fa fa-fw fa-user-plus"></i>免费注册
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">WELCOME YOU</h1>
        <p class="lead">Life is short. You need Python.</p>
        <hr class="my-4">
        <p>Django makes it easier to build better Web apps more quickly and with less code.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </p>
    </div>
{% endblock %}

templates/paginator.html
<div class="pagination">
    <nav>
        <ul class="pagination pagination-sm">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
                        <span aria_hidden="true">&laquo;</span></a>
                </li>
            {% endif %}

            {% for page_num in page.paginator.page_range %}
                {% if page_num == page.number %}
                    <li class="page-item active"><a class="page-link" href="?page={{ page_num }}">{{page_num}}</a> </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{page_num}}</a> </li>
                {% endif %}
            {% endfor %}

            {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
                        <span aria_hidden="true">&raquo;</span></a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>