account/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView
# namespace
app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html'), name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('register/', views.register, name='register'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image/', views.my_image, name='my_image'),
]

article/urls.py
from . import views, list_views
from django.urls import path

# namespace
app_name = 'article'

urlpatterns = [
    # 后台
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<id>/<slug>/', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('redit-article/<article_id>/', views.redit_article, name='redit_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag'),
    # 前台
    path('list-article-titles/', list_views.article_titles, name='article_titles'),
    path('list-article-titles/<username>/', list_views.article_titles, name='author_titles'),
    path('list-article-detail/<id>/<slug>/', list_views.article_detail, name='list_article_detail'),
    path('like-article/', list_views.like_article, name='like_article'),
    # 发表评论
    path('post-comment/<article_id>/', list_views.post_comment, name='post_comment'),
]

blog/urls.py
from . import views
from django.urls import path

# namespace
app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<article_id>', views.blog_acticle, name='blog_detail'),
]

course/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
# namespace
app_name = 'course'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='course/about.html'), name='about'),
    path('course-list/', views.CourseListView.as_view(), name='course_list'),
    path('manage-course/', views.ManageCourseListView.as_view(), name='manage_course'),
    path('create-course/', views.CreateCourseView.as_view(), name='create_course'),
    path('delete-course/<pk>', views.DeleteCourseView.as_view(), name='delete_course'),
    path('create-lesson/', views.CreateLessonView.as_view(), name='create_lesson'),
]

image/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'image'

urlpatterns = [
    path('list-images/', views.list_images, name='list_images'),
    path('upload-image/', views.upload_image, name='upload_image'),
    path('del-image/', views.del_image, name='del_image'),
    path('images/', views.falls_images, name='falls_images'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
# 对于显示静态文件非常重要
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('blog/', include('blog.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
# Create your models here.


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column',
                             on_delete=models.CASCADE, verbose_name='作者')
    column = models.CharField('栏目', max_length=200)
    created = models.DateField('创建时间', auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name='tag', on_delete=models.CASCADE, verbose_name='作者')
    tag = models.CharField('标签', max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name='article',
                               on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField('标题', max_length=200)
    slug = models.SlugField('Slug', max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column',
                               on_delete=models.CASCADE, verbose_name='栏目')
    body = models.TextField()
    created = models.DateTimeField('创建时间', default=timezone.now)
    updated = models.DateTimeField('修改时间', auto_now=True)
    users_like = models.ManyToManyField(User, related_name='articles_like', blank=True, verbose_name='点赞')
    total_views = models.PositiveIntegerField('浏览量', default=0)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True, verbose_name='文章标签')

    class Meta:
        ordering = ['-updated']
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail', args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name='comments', on_delete=models.CASCADE, verbose_name='文章')
    commentator = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE, verbose_name='评论人')
    body = models.TextField()
    created = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag
from django.forms import TextInput


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ['column']


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ['title', 'body']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ['tag']

        widgets = {
            'tag': TextInput(attrs={'class': 'form-control form-control-sm'}),
        }

article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm
import json
# Create your views here.
"""这里编写的都是用户后台的视图：栏目管理/发布文章/文章管理"""


@login_required
@csrf_exempt
def article_column(request):
    """栏目列表 & 新增栏目"""
    if request.method == "GET":
        column_list = ArticleColumn.objects.filter(user=request.user)
        paginator = Paginator(column_list, 10)  # 实例化一个分页对象, 每页显示10个
        page = request.GET.get('page')  # 从URL通过get页码，如?page=3
        try:
            current_page = paginator.page(page)  # 获取指定页面内容，其参数必须>=1的整数
            columns = current_page.object_list  # 获取当前页对应的所有记录
        except PageNotAnInteger:  # 页码不是整数，捕获异常
            current_page = paginator.page(1)
            columns = current_page.object_list
        except EmptyPage:  # 页码为空，捕获异常
            current_page = paginator.page(paginator.num_pages)  # 返回页数
            columns = current_page.object_list
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {"columns": columns, "column_form": column_form,
                                                                      "page": current_page})
    if request.method == "POST":
        column_name = request.POST['column']
        if column_name:
            columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
            if columns:
                return HttpResponse('2')
            else:
                ArticleColumn.objects.create(user=request.user, column=column_name)
                return HttpResponse('1')
        else:
            return HttpResponse('3')


@login_required
@require_POST
@csrf_exempt
def rename_article_column(request):
    """修改栏目"""
    column_name = request.POST["column_name"]
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required
@require_POST
@csrf_exempt
def del_article_column(request):
    """删除栏目"""
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required
@csrf_exempt
def article_post(request):
    """新增文章"""
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, 'article/column/article_post.html',
                      {'article_post_form': article_post_form, 'article_columns': article_columns,
                       'article_tags': article_tags})


@login_required
def article_list(request):
    """文章列表"""
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)  # 实例化一个分页对象, 每页显示10个
    page = request.GET.get('page')  # 从URL通过get页码，如?page=3
    try:
        current_page = paginator.page(page)     # 获取指定页面内容，其参数必须>=1的整数
        articles = current_page.object_list  # 获取当前页对应的所有记录
    except PageNotAnInteger:        # 页码不是整数，捕获异常
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:       # 页码为空，捕获异常
        current_page = paginator.page(paginator.num_pages)      # 返回页数
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {'articles': articles, 'page': current_page})


@login_required
def article_detail(request, id, slug):
    """文章详情"""
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, 'article/column/article_detail.html', {'article': article})


@login_required
@require_POST
@csrf_exempt
def del_article(request):
    """删除文章"""
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required
@csrf_exempt
def redit_article(request, article_id):
    """修改文章"""
    if request.method == "GET":
        article_columns = request.user.article_column.all()     # 该用户的所有栏目
        article = ArticlePost.objects.get(id=article_id)        # 当前ID的这篇文章的实例
        this_article_form = ArticlePostForm(initial={"title": article.title})  # 当前ID的这篇文章实例的表单，初始标题
        this_article_column = article.column        # 当前ID的这篇文章实例的默认栏目
        user_tags = request.user.tag.all()       # 该用户的所有标签，注意：不是这篇文章的所有标签
        return render(request, 'article/column/redit_article.html', {"article": article,
                                                                     "article_columns": article_columns,
                                                                     "this_article_column": this_article_column,
                                                                     "this_article_form": this_article_form,
                                                                     'user_tags': user_tags})
    else:
        edited_article = ArticlePost.objects.get(id=article_id)
        edited_article.article_tag.clear()      # 先清空此文章的所有标签，如果不清空，就永远是累加
        try:
            edited_article.column = request.user.article_column.get(id=request.POST['column_id'])
            edited_article.title = request.POST['title']
            edited_article.body = request.POST['body']
            edited_article.save()
            tags = request.POST['tags']
            if tags:
                for atag in json.loads(tags):
                    tag = request.user.tag.get(tag=atag)
                    edited_article.article_tag.add(tag)
            return HttpResponse("1")
        except:
            return HttpResponse("2")


@login_required
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html', {'article_tags': article_tags,
                                                             'article_tag_form': article_tag_form})
    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("数据没有被保存")
        else:
            return HttpResponse("对不起，表单不合法")


@login_required
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

templates/article/base.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'layer/theme/default/layer.css' %}">
    {% block css %}{% endblock %}
    <style>
        .layui-layer { font-size:0.875rem;}
        .layui-layer a:not([href]):not([tabindex]) { color:#FFF;}
        .layui-layer a:not([href]):not([tabindex]):last-child { color:#333;}
        .layui-layer a.layui-layer-btn0:not([href]):not([tabindex]):last-child { color:#FFF;}
    </style>
</head>
<body>
    {% include "article/header.html" %}
    <div class="container">
        <div class="row">
            <div class="col-md-2 border-right">
                {% include 'article/leftslider.html' %}
            </div>
            <div class="col-md-10">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'dist/js/popper.min.js' %}"></script>
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/theme/layer.js' %}"></script>
{% block js %}{% endblock %}
</html>

templates/article/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4" role="navigation">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/bootstrap-solid.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            管理后台
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_column' %}">文章管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'image:list_images' %}">图片管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'course:manage_course' %}">课程管理</a>
                </li>
            </ul>
            <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">
                            <i class="fa fa-fw fa-home"></i> 网站首页
                        </a>
                    </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-fw fa-user-circle-o"></i>
                            {% if user.last_name %}
                                <span class="small">{{ user.last_name }}{{ user.first_name }}</span>
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'account:my_information' %}">
                                <i class="fa fa-fw fa-user"></i> 个人中心
                            </a>
                            <a class="dropdown-item" href="{% url 'account:edit_my_information' %}">
                                <i class="fa fa-fw fa-pencil"></i> 修改信息
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account:user_logout' %}">
                                <i class="fa fa-fw fa-sign-out"></i> 账号退出
                            </a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_login' %}">
                            <i class="fa fa-fw fa-sign-in"></i>请登录
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:register' %}">
                            <i class="fa fa-fw fa-user-plus"></i>免费注册
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/article/layer_iframe.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'layer/theme/default/layer.css' %}">
    <style>
        .layui-layer { font-size:0.875rem;}
        .layui-layer a:not([href]):not([tabindex]) { color:#FFF;}
        .layui-layer a:not([href]):not([tabindex]):last-child { color:#333;}
        .layui-layer a.layui-layer-btn0:not([href]):not([tabindex]):last-child { color:#FFF;}
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'dist/js/popper.min.js' %}"></script>
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/theme/layer.js' %}"></script>
{% block js %}{% endblock %}
</html>

templates/article/leftslider.html
<nav id="navbar-example3" class="navbar navbar-light bg-light">
    <span class="navbar-brand small"><i class="fa fa-fw fa-newspaper-o"></i> 文章管理</span>
    <nav class="nav nav-pills flex-column small">
            <a class="nav-link ml-3 my-1 text-dark" href="{% url 'article:article_column' %}">
                <i class="fa fa-fw fa-columns"></i> 栏目管理
            </a>
            <a class="nav-link ml-3 my-1 text-dark" href="{% url 'article:article_post' %}">
                <i class="fa fa-fw fa-paper-plane"></i> 发布文章
            </a>
            <a class="nav-link ml-3 my-1 text-dark" href="{% url 'article:article_list' %}">
                <i class="fa fa-fw fa-list-ol"></i> 文章列表
            </a>
            <a class="nav-link ml-3 my-1 text-dark" href="{% url 'article:article_tag' %}">
                <i class="fa fa-fw fa-tags"></i> 文章标签
            </a>
    </nav>
    <span class="navbar-brand small"><i class="fa fa-fw fa-picture-o"></i> 图片管理</span>
    <nav class="nav nav-pills flex-column small">
        <a class="nav-link ml-3 my-1 text-dark" href="{% url 'image:list_images' %}">
            <i class="fa fa-fw fa-magnet"></i> 爬取网图
        </a>
    </nav>
    <span class="navbar-brand small"><i class="fa fa-fw fa-file-video-o"></i> 课程管理</span>
    <nav class="nav nav-pills flex-column small">
        <a class="nav-link ml-3 my-1 text-dark" href="{% url 'course:manage_course' %}">
            <i class="fa fa-fw fa-file-video-o"></i> 课程管理
        </a>
        <a class="nav-link ml-3 my-1 text-dark" href="{% url 'course:create_lesson' %}">
            <i class="fa fa-fw fa-file-video-o"></i> 内容发布
        </a>
    </nav>
</nav>